"""
PlantVG core -- single-file bundle for Google Colab.

AUTO-GENERATED by build_core.py from the plantvg package. Do not edit directly;
edit the package modules and regenerate.

Python port of PlantVG.m -- Stubbs, C.J. & Benzecry, A., Fairleigh Dickinson
University. https://github.com/cstubbsFDU/PlantVG
"""
from __future__ import annotations
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable
import numpy as np
from scipy import ndimage as ndi
from scipy import stats


# ======================================================================
# --- imaging.py
# ======================================================================





# ---------------------------------------------------------------------------
# Section 1 -- binarization
# ---------------------------------------------------------------------------

def graythresh(img: np.ndarray, num_bins: int = 256) -> float:
    """Otsu threshold, reimplemented to match MATLAB's ``graythresh`` exactly.

    MATLAB differs from ``skimage.filters.threshold_otsu`` in two ways that
    matter at the boundary of a tie:

    1. It always uses a 256-bin histogram over the *class range* of the image
       (0..255 for uint8), not over ``[img.min(), img.max()]``.
    2. On ties it takes the **mean** of all maximizing bin indices, which can
       land the threshold halfway between two bins.

    Returns
    -------
    float
        Normalized threshold in ``[0, 1]``, as MATLAB does.
    """
    img = np.asarray(img)
    if img.dtype != np.uint8:
        raise TypeError(f"graythresh expects uint8, got {img.dtype}")

    counts = np.bincount(img.ravel(), minlength=num_bins).astype(np.float64)
    total = counts.sum()
    if total == 0:
        return 0.0

    p = counts / total
    omega = np.cumsum(p)
    # MATLAB uses 1-based bin centres (1..num_bins) here.
    mu = np.cumsum(p * np.arange(1, num_bins + 1, dtype=np.float64))
    mu_t = mu[-1]

    # Suppress the 0/0 at omega == 0 and omega == 1; MATLAB produces NaN there
    # and max() ignores NaN.
    with np.errstate(divide="ignore", invalid="ignore"):
        sigma_b_squared = (mu_t * omega - mu) ** 2 / (omega * (1.0 - omega))

    if np.all(np.isnan(sigma_b_squared)):
        return 0.0

    maxval = np.nanmax(sigma_b_squared)
    # MATLAB: idx = mean(find(sigma_b_squared == maxval)), 1-based.
    idx = np.mean(np.flatnonzero(sigma_b_squared == maxval)) + 1.0
    return (idx - 1.0) / (num_bins - 1.0)


def imbinarize(img: np.ndarray) -> np.ndarray:
    """Global Otsu binarization matching MATLAB ``imbinarize(I)`` for uint8.

    MATLAB computes ``BW = im2double(I) > graythresh(I)``, i.e. a *strict*
    greater-than against the normalized level.
    """
    img = np.asarray(img)
    level = graythresh(img)
    return (img.astype(np.float64) / 255.0) > level


def read_binary_image(path) -> tuple[np.ndarray, np.ndarray]:
    """Port of ``I = imread(p); BW = imbinarize(I(:,:,1))``.

    MATLAB takes the **first channel only** -- the red channel for an RGB or
    RGBA image, not a luminance conversion. Reproduced exactly here.

    Returns
    -------
    (raw, bw)
        ``raw`` is the image as read; ``bw`` is the boolean binarization of its
        first channel.
    """

    raw = np.array(__import__("PIL.Image", fromlist=["Image"]).open(path))
    channel = raw[:, :, 0] if raw.ndim == 3 else raw
    if channel.dtype != np.uint8:
        raise TypeError(f"expected uint8 image data, got {channel.dtype}")
    return raw, imbinarize(channel)


# ---------------------------------------------------------------------------
# Section 2 -- hole filling and boundary tracing
# ---------------------------------------------------------------------------

def imfill_holes(bw: np.ndarray) -> np.ndarray:
    """Port of ``imfill(BW, 'holes')``.

    MATLAB's default hole-filling for a 2-D logical image uses 8-connectivity
    for the *background* flood, which corresponds to 4-connectivity on the
    foreground. ``binary_fill_holes`` with the default cross structure matches.
    """
    return ndi.binary_fill_holes(np.asarray(bw, dtype=bool))


# Moore neighbourhood offsets in clockwise order starting due north,
# expressed as (drow, dcol).
_MOORE = np.array(
    [(-1, 0), (-1, 1), (0, 1), (1, 1), (1, 0), (1, -1), (0, -1), (-1, -1)],
    dtype=np.int64,
)


def _label_matlab_order(bw: np.ndarray, connectivity: int) -> tuple[np.ndarray, int]:
    """Connected-component labelling in MATLAB's ``bwlabel`` ordering.

    MATLAB numbers components in the order their first pixel is met scanning
    **column-major** (down each column, left to right). ``scipy.ndimage.label``
    scans row-major. Labelling the transpose and transposing back reproduces
    MATLAB's order.
    """
    structure = np.ones((3, 3), bool) if connectivity == 8 else ndi.generate_binary_structure(2, 1)
    lab_t, n = ndi.label(np.asarray(bw, bool).T, structure=structure)
    return lab_t.T, n


def _trace_one(mask: np.ndarray, start: tuple[int, int]) -> np.ndarray:
    """Moore-neighbour boundary trace with Jacob's stopping criterion.

    This is the algorithm MATLAB's ``bwboundaries`` uses. It walks the outer
    ring of foreground pixels of a single connected component and returns them
    in order, with the start pixel repeated at the end to close the loop --
    again matching MATLAB.

    Parameters
    ----------
    mask
        Boolean image containing exactly the component of interest.
    start
        ``(row, col)`` of the first component pixel in column-major scan order.
    """
    h, w = mask.shape
    sr, sc = start

    def solid(r, c):
        return 0 <= r < h and 0 <= c < w and mask[r, c]

    # The start pixel is the topmost pixel of the leftmost occupied column, so
    # its west neighbour is guaranteed background: begin backtracking there.
    backtrack = (sr, sc - 1)

    boundary = [(sr, sc)]
    current = (sr, sc)

    # Jacob's criterion: stop when we re-enter the start pixel from the same
    # direction we originally left it. Track the first departure separately.
    first_step = None
    max_steps = 4 * h * w  # generous guard against pathological input

    for _ in range(max_steps):
        # Index of the backtrack pixel within the current pixel's Moore ring.
        offset = (backtrack[0] - current[0], backtrack[1] - current[1])
        idx = int(np.flatnonzero((_MOORE == np.array(offset)).all(axis=1))[0])

        found = None
        for k in range(1, 9):
            j = (idx + k) % 8
            cand = (current[0] + _MOORE[j][0], current[1] + _MOORE[j][1])
            if solid(*cand):
                found = cand
                # The pixel we just rejected becomes the new backtrack.
                prev = (idx + k - 1) % 8
                backtrack = (current[0] + _MOORE[prev][0], current[1] + _MOORE[prev][1])
                break

        if found is None:
            # Isolated single pixel.
            break

        if first_step is None:
            first_step = found
        elif current == (sr, sc) and found == first_step:
            # Back at the start, leaving the same way: the loop is closed.
            break

        current = found
        boundary.append(current)

        if len(boundary) > 2 and current == (sr, sc):
            # Cheap early exit for simple loops; Jacob's criterion above is the
            # authoritative one for figure-eight shapes.
            nxt_offset = (backtrack[0] - current[0], backtrack[1] - current[1])
            nxt_idx = int(np.flatnonzero((_MOORE == np.array(nxt_offset)).all(axis=1))[0])
            for k in range(1, 9):
                j = (nxt_idx + k) % 8
                cand = (current[0] + _MOORE[j][0], current[1] + _MOORE[j][1])
                if solid(*cand):
                    if cand == first_step:
                        boundary.pop()
                        return np.array(boundary + [(sr, sc)], dtype=np.float64)
                    break

    # Close the loop the way MATLAB does.
    if boundary[0] != boundary[-1]:
        boundary.append(boundary[0])
    return np.array(boundary, dtype=np.float64)


def bwboundaries(bw: np.ndarray, connectivity: int = 8) -> list[np.ndarray]:
    """Port of MATLAB ``bwboundaries(BW)`` (objects only).

    Returns one ``(N, 2)`` float array per connected component, in ``(row, col)``
    order and **0-based**, with the first point repeated at the end.

    Hole boundaries are not returned. In PlantVG this is safe and exact: every
    call site traces an image that has already been through ``imfill(...,
    'holes')``, so no holes remain to trace.
    """
    labels, n = _label_matlab_order(bw, connectivity)
    out: list[np.ndarray] = []

    for lab in range(1, n + 1):
        component = labels == lab
        # First pixel in column-major order == MATLAB's trace start point.
        cols, rows = np.nonzero(component.T)
        start = (int(rows[0]), int(cols[0]))
        out.append(_trace_one(component, start))

    return out

# ======================================================================
# --- geometry.py
# ======================================================================





# ---------------------------------------------------------------------------
# poly2mask
# ---------------------------------------------------------------------------

def poly2mask(
    rows: np.ndarray,
    cols: np.ndarray,
    shape: tuple[int, int],
    x_rule: str = "left",
) -> np.ndarray:
    """MATLAB-compatible ``poly2mask``.

    Parameters
    ----------
    rows, cols
        Polygon vertices, 0-based, in the (row, col) order ``bwboundaries``
        returns. The polygon is closed automatically if it isn't already.
    shape
        ``(H, W)`` of the output mask.
    x_rule
        Which side of a span boundary is inclusive when a pixel centre falls
        exactly on it. ``"left"`` -> ``a <= px < b``; ``"right"`` -> ``a < px <= b``.
        These produce equal pixel *counts* but different pixel *sets*.

    Notes
    -----
    Vectorized over scanlines: all edges are tested against all rows at once,
    which is roughly 100x faster than the per-row Python loop and matters
    because Section 6 rasterizes one polygon per cell.
    """
    H, W = shape
    r = np.asarray(rows, dtype=np.float64)
    c = np.asarray(cols, dtype=np.float64)

    if r[0] != r[-1] or c[0] != c[-1]:
        r = np.append(r, r[0])
        c = np.append(c, c[0])

    r0, r1 = r[:-1], r[1:]
    c0, c1 = c[:-1], c[1:]

    horizontal = r0 == r1
    r0, r1, c0, c1 = r0[~horizontal], r1[~horizontal], c0[~horizontal], c1[~horizontal]
    if r0.size == 0:
        return np.zeros((H, W), bool)

    lo = np.minimum(r0, r1)
    hi = np.maximum(r0, r1)

    y = np.arange(H, dtype=np.float64)[:, None]          # (H, 1)
    # MATLAB's rule: lower endpoint exclusive, upper endpoint inclusive.
    hits = (lo[None, :] < y) & (y <= hi[None, :])        # (H, E)

    with np.errstate(divide="ignore", invalid="ignore"):
        xs = c0[None, :] + (y - r0[None, :]) * ((c1 - c0) / (r1 - r0))[None, :]

    xs = np.where(hits, xs, np.inf)
    xs.sort(axis=1)

    px = np.arange(W, dtype=np.float64)[None, :]         # (1, W)
    mask = np.zeros((H, W), bool)

    n_cross = hits.sum(axis=1)
    for k in range(0, int(n_cross.max()), 2):
        a = xs[:, k][:, None]
        b = xs[:, k + 1][:, None] if k + 1 < xs.shape[1] else np.full_like(a, np.inf)
        valid = np.isfinite(a) & np.isfinite(b)
        if x_rule == "left":
            span = (px >= a) & (px < b)
        else:
            span = (px > a) & (px <= b)
        mask |= span & valid

    return mask


# ---------------------------------------------------------------------------
# Section 3 -- cell lengths from the longitudinal image
# ---------------------------------------------------------------------------

def cell_heights(boundaries: list[np.ndarray], image_height: int) -> tuple[np.ndarray, np.ndarray]:
    """Port of the cell-length extraction loop.

    A cell is counted only if its trace is fully interior in the row direction,
    so cells clipped by the top or bottom image edge don't skew the
    distribution. MATLAB's test is ``max(rows) < H && min(rows) > 1`` in 1-based
    indexing; translated to 0-based that is ``max < H-1 && min > 0``.

    Returns
    -------
    (heights, counted)
        ``heights`` is the height of each *accepted* cell, in source order.
        ``counted`` is a boolean mask over ``boundaries`` marking which were
        accepted -- needed to reproduce MATLAB's overlay plot.
    """
    heights: list[float] = []
    counted = np.zeros(len(boundaries), dtype=bool)

    for i, b in enumerate(boundaries):
        rmin, rmax = b[:, 0].min(), b[:, 0].max()
        if rmax < image_height - 1 and rmin > 0:
            heights.append(rmax - rmin)
            counted[i] = True

    return np.asarray(heights, dtype=np.float64), counted


def filter_heights(
    heights: np.ndarray,
    lower: float | None = None,
    upper: float | None = None,
    length_factor: float = 1.0,
) -> tuple[np.ndarray, float, float]:
    """Apply the cell-length factor and the user's outlier cut.

    This replaces the ``hist`` + ``ginput(2)`` interaction. ``lower``/``upper``
    are the two values the user would have clicked on the histogram; ``None``
    means no cut on that side.

    Order of operations
    -------------------
    ``length_factor`` is applied **once, up front**, so that the histogram, the
    user's thresholds, and the returned heights are all in the same units.

    This corrects a bug in PlantVG.m, which plotted ``lengthFactor*heightPre``
    but compared the *unscaled* ``heightPre`` against the clicked thresholds,
    then applied ``lengthFactor`` a second time to the survivors. The effect was
    invisible at the default ``lengthFactor = 1.0`` and wrong everywhere else:
    at ``lengthFactor = 2``, clicking a cut at 100 on the histogram actually cut
    at 50, and the surviving cells were then doubled again.

    Returns
    -------
    (height, avg, std)
        ``std`` uses MATLAB's N-1 normalization (``ddof=1``), not numpy's default.
    """
    scaled = length_factor * np.asarray(heights, dtype=np.float64)

    keep = np.ones(scaled.shape, bool)
    if lower is not None:
        keep &= scaled > lower
    if upper is not None:
        keep &= scaled < upper

    height = scaled[keep]
    if height.size == 0:
        lo_txt = "-inf" if lower is None else f"{lower:.1f}"
        hi_txt = "+inf" if upper is None else f"{upper:.1f}"
        raise ValueError(
            f"The cell length range you chose ({lo_txt} to {hi_txt} pixels) excludes "
            f"every cell. The measured lengths run from {scaled.min():.1f} to "
            f"{scaled.max():.1f} pixels -- widen the slider to cover some of that range."
        )

    avg = float(np.mean(height))
    std = float(np.std(height, ddof=1)) if height.size > 1 else 0.0
    return height, avg, std

# ======================================================================
# --- distributions.py
# ======================================================================


from dataclasses import dataclass
from typing import Callable




# ---------------------------------------------------------------------------
# MATLAB-compatible rounding
# ---------------------------------------------------------------------------

def matlab_round(x):
    """Round half **away from zero**, as MATLAB's ``round`` does.

    ``numpy.round`` uses banker's rounding (half to *even*): ``np.round(2.5)``
    is 2, whereas MATLAB's ``round(2.5)`` is 3. Every ``round(...rnd(...))`` call
    in PlantVG.m draws from a continuous distribution, so exact halves are rare
    -- but ``round(rand()*Avg)`` and the fillet arithmetic hit them often enough
    to matter, and the bias is systematic rather than random.
    """
    x = np.asarray(x, dtype=np.float64)
    return np.trunc(x + np.copysign(0.5, x))


# ---------------------------------------------------------------------------
# Fitted distribution
# ---------------------------------------------------------------------------

@dataclass
class FittedDistribution:
    """A fitted cell-length distribution and its sampler.

    Attributes
    ----------
    name
        Display name, one of :data:`DISTRIBUTIONS`.
    params
        Parameters in **MATLAB's** order, matching ``pd.Params`` in PlantVG.m, so
        that anything printed or logged lines up with the original tool.
    sample
        ``sample(rng) -> float``, one draw in MATLAB's parameterization.
    """

    name: str
    params: tuple[float, ...]
    sample: Callable[[np.random.Generator], float]

    def step_size(self, rng: np.random.Generator) -> int:
        """One end-cap step: a draw, MATLAB-rounded, floored at 1.

        The floor reproduces PlantVG.m's guard against a zero or negative step
        sending the ``while current_pos <= voxelDepth`` loop into an infinite
        spin.
        """
        return max(1, int(matlab_round(self.sample(rng))))


DISTRIBUTIONS = ("Normal", "Exponential", "Gamma", "Poisson", "Weibull")


def fit_distribution(height: np.ndarray, name: str) -> FittedDistribution:
    """Port of ``pd = fitdist(height', name); params = pd.Params``.

    Parameters
    ----------
    height
        Filtered, length-factor-scaled cell heights.
    name
        One of :data:`DISTRIBUTIONS` (case-insensitive).
    """
    x = np.asarray(height, dtype=np.float64).ravel()
    if x.size == 0:
        raise ValueError("cannot fit a distribution to an empty height vector")

    key = name.strip().lower()

    if key == "normal":
        # MATLAB normfit: mu = sample mean, sigma with the **N-1** denominator.
        # scipy.stats.norm.fit would return the MLE (N denominator) instead.
        mu = float(np.mean(x))
        sigma = float(np.std(x, ddof=1)) if x.size > 1 else 0.0
        return FittedDistribution(
            "Normal", (mu, sigma),
            lambda rng, mu=mu, sigma=sigma: rng.normal(mu, sigma),
        )

    if key == "exponential":
        # MATLAB expfit / exprnd are parameterized by the **mean** mu.
        # scipy calls the same quantity `scale`.
        mu = float(np.mean(x))
        return FittedDistribution(
            "Exponential", (mu,),
            lambda rng, mu=mu: rng.exponential(mu),
        )

    if key == "gamma":
        # MATLAB gamfit -> [a, b] = [shape, scale]; gamrnd(a, b) likewise.
        # scipy needs floc=0 to fit the same two-parameter family MATLAB fits.

        a, loc, b = stats.gamma.fit(x, floc=0)
        a, b = float(a), float(b)
        return FittedDistribution(
            "Gamma", (a, b),
            lambda rng, a=a, b=b: rng.gamma(a, b),
        )

    if key == "poisson":
        # MATLAB poissfit: lambda = sample mean. fitdist('Poisson') requires
        # non-negative integer data and errors otherwise -- worth surfacing
        # early, because a non-integer lengthFactor makes the heights fractional.
        if np.any(x < 0) or np.any(x != np.floor(x)):
            raise ValueError(
                "The Poisson distribution only works with whole-number cell "
                "lengths, but the cell length factor has made them fractional.\n\n"
                "Either set the cell length factor to a whole number (1, 2, 3...), "
                "or choose a different distribution -- Normal and Gamma both handle "
                "fractional lengths."
            )
        lam = float(np.mean(x))
        return FittedDistribution(
            "Poisson", (lam,),
            lambda rng, lam=lam: float(rng.poisson(lam)),
        )

    if key == "weibull":
        # THE SWAP. MATLAB wblfit -> [a, b] = [**scale**, **shape**], and
        # wblrnd(a, b) takes them in that order. scipy.stats.weibull_min is
        # (c=**shape**, loc, scale). Passing MATLAB's tuple straight into scipy
        # positionally silently fits/samples the wrong distribution.

        shape_c, loc, scale_a = stats.weibull_min.fit(x, floc=0)
        a, b = float(scale_a), float(shape_c)   # MATLAB order: (scale, shape)
        return FittedDistribution(
            "Weibull", (a, b),
            lambda rng, a=a, b=b: a * rng.weibull(b),
        )

    raise ValueError(
        f"unknown distribution {name!r}; expected one of {DISTRIBUTIONS}"
    )

# ======================================================================
# --- voxel.py
# ======================================================================






# ---------------------------------------------------------------------------
# Section 5 -- end cap locations
# ---------------------------------------------------------------------------

def generate_end_caps(
    n_cells: int,
    voxel_depth: int,
    fitted: FittedDistribution,
    avg: float,
    rng: np.random.Generator,
) -> np.ndarray:
    """Port of the ``endCapArray`` construction.

    Each cell gets an independent random walk up the voxel column: start at a
    uniform random offset within one mean cell length, mark an end cap, then
    step by a draw from the fitted distribution until past the top.

    Returns
    -------
    ndarray of bool, shape ``(n_cells, voxel_depth)``
        Column ``k`` corresponds to MATLAB's 1-based slice ``k+1``.
    """
    caps = np.zeros((n_cells, voxel_depth), dtype=bool)

    for i in range(n_cells):
        # MATLAB: current_pos = round(rand() * Avg), 1-based slice index.
        pos = int(matlab_round(rng.random() * avg))

        while pos <= voxel_depth:
            # MATLAB guards `current_pos >= 1` because round(rand()*Avg) can be 0.
            if pos >= 1:
                caps[i, pos - 1] = True
            pos += fitted.step_size(rng)

    return caps


# ---------------------------------------------------------------------------
# Section 6 -- fillet profiles
# ---------------------------------------------------------------------------

def fillet_arrays(
    end_cap_vector: np.ndarray,
    radius: int,
    cell_wall_thickness: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Port of the ``subInner`` / ``subOuter`` / ``fillArray`` construction.

    These three arrays say, for each slice, how deeply to erode the inner mask,
    how deeply to erode the outer mask, and whether the cell is solid there
    (i.e. inside an end cap, so the lumen is not punched out).

    The quarter-sine profiles give the end-cap fillet its curvature. Written
    with MATLAB's 1-based slice index ``k`` throughout to keep the index
    arithmetic legible against the original.

    Note that the bounds test guards *both* the lower and upper write index with
    a single condition, so when one side falls outside the volume neither side
    is written. That asymmetry is MATLAB's and is preserved deliberately.
    """
    depth = len(end_cap_vector)
    sub_inner = np.zeros(depth, dtype=np.float64)
    sub_outer = np.zeros(depth, dtype=np.float64)
    fill_array = np.zeros(depth, dtype=bool)

    thk = int(matlab_round(cell_wall_thickness / 2))
    ri = int(radius)
    ro = ri + thk

    for k in range(1, depth + 1):
        if not end_cap_vector[k - 1]:
            continue

        # --- inner mask erosion profile
        for j in range(1, ri + 1):
            if (k - thk - ri + j) > 0 and (k + thk + ri - j) < depth + 1:
                value = np.sin(j * np.pi / 2 / ri) * ri
                sub_inner[(k - thk - ri + j) - 1] = value
                sub_inner[(k + thk + ri - j) - 1] = value

        if (k - thk) > 0 and (k + thk) < depth + 1:
            sub_inner[(k - thk) - 1 : (k + thk)] = ri

        # --- outer mask erosion profile
        for j in range(1, ri + thk + 1):
            if (k - thk - ri + j) > 0 and (k + thk + ri - j) < depth + 1:
                value = np.sin(j * np.pi / 2 / (ri + cell_wall_thickness)) * (ri + thk)
                sub_outer[(k - ro + j) - 1] = value
                sub_outer[(k + ro - j) - 1] = value

        # --- solid (end cap) region
        if (k - thk) > 0 and (k + thk) < depth + 1:
            fill_array[(k - thk) - 1 : (k + thk)] = True

    return sub_inner, sub_outer, fill_array


# ---------------------------------------------------------------------------
# Section 6 -- erosion via distance transform
# ---------------------------------------------------------------------------

def cityblock_erosion_depth(mask: np.ndarray) -> np.ndarray:
    """Number of ``bwperim`` peels each pixel survives.

    ``peel(mask, n)`` -- the MATLAB loop -- equals ``cityblock_erosion_depth(mask) > n``.
    Outside-the-array counts as foreground, matching ``bwperim``'s in-image-only
    neighbour test, so pixels on the image border never erode.
    """
    return ndi.distance_transform_cdt(mask, metric="taxicab")


def _disk_dilate(points_rc: np.ndarray, shape: tuple[int, int], radius: float) -> np.ndarray:
    """Union of Euclidean disks of ``radius`` centred on each ``(row, col)`` point.

    Equivalent to PlantVG.m's per-boundary-pixel ``sqrt(...) <= cellWallThickness``
    accumulation, but computed as a single distance transform.

    PlantVG.m *sums* the disks, so overlaps hold values above 1. That is
    immaterial: every downstream consumer (``imfill``, ``bwperim``, and the final
    ``uint8(x*255)`` which saturates at 255) treats any nonzero value
    identically, so the boolean union produces a bit-identical TIFF.
    """
    seeds = np.ones(shape, dtype=bool)
    seeds[points_rc[:, 0].astype(int), points_rc[:, 1].astype(int)] = False
    return ndi.distance_transform_edt(seeds) <= radius


# ---------------------------------------------------------------------------
# Section 6 -- the voxel matrix
# ---------------------------------------------------------------------------

def build_voxel_matrix(
    boundaries: list[np.ndarray],
    end_cap_array: np.ndarray,
    shape: tuple[int, int],
    voxel_depth: int,
    wall_thickness: int,
    wall_variation: int,
    radius: int,
    rng: np.random.Generator,
    progress: bool = False,
) -> np.ndarray:
    """Port of the main voxel construction loop.

    Returns
    -------
    ndarray of bool, shape ``(voxel_depth, H, W)``
        Slice-major, ready for ``tifffile``. MATLAB's ``VoxelMatrix`` is
        ``(H, W, voxel_depth)``; the axis order is changed here because every
        consumer wants slices.
    """
    H, W = shape
    volume = np.zeros((voxel_depth, H, W), dtype=bool)

    for i, boundary in enumerate(boundaries):
        # PlantVG.m: skip slivers that aren't really an area.
        if len(boundary) <= 4:
            continue

        # --- per-cell wall thickness randomization
        variation = int(matlab_round(rng.random() * 2 * wall_variation - wall_variation))
        cell_wall_thickness = max(1, wall_thickness + variation)

        inner = poly2mask(boundary[:, 0], boundary[:, 1], shape)
        outer = _disk_dilate(boundary, shape, cell_wall_thickness) | inner

        # Work in the cell's bounding box. Erosion is local, so this is exact --
        # but pad by one so that a cell touching the crop edge still sees the
        # background beyond it. Cells genuinely touching the *image* edge keep
        # MATLAB's no-erode behaviour because the pad is clipped there.
        rows = np.flatnonzero(outer.any(axis=1))
        cols = np.flatnonzero(outer.any(axis=0))
        r0, r1 = max(0, rows[0] - 1), min(H, rows[-1] + 2)
        c0, c1 = max(0, cols[0] - 1), min(W, cols[-1] + 2)
        sl = (slice(r0, r1), slice(c0, c1))

        outer_c, inner_c = outer[sl], inner[sl]
        depth_outer = cityblock_erosion_depth(outer_c)
        depth_inner = cityblock_erosion_depth(inner_c)

        sub_inner, sub_outer, fill_array = fillet_arrays(
            end_cap_array[i], radius, cell_wall_thickness
        )

        # MATLAB's `for j = 1:subOuter(k)` iterates floor(subOuter(k)) times.
        n_outer = np.floor(sub_outer).astype(np.int64)
        n_inner = np.floor(sub_inner).astype(np.int64)

        # Most slices share the same (erode_outer, erode_inner, filled) triple,
        # so compute each distinct layer once and reuse it.
        cache: dict[tuple[int, int, bool], np.ndarray] = {}
        for k in range(voxel_depth):
            key = (int(n_outer[k]), int(n_inner[k]), bool(fill_array[k]))
            layer = cache.get(key)
            if layer is None:
                layer = depth_outer > key[0]
                if not key[2]:
                    layer = layer & ~(depth_inner > key[1])
                cache[key] = layer
            volume[k][sl] |= layer

        if progress:
            print(f"  cell {i + 1}/{len(boundaries)}  wall={cell_wall_thickness}px  "
                  f"{len(cache)} distinct layers", flush=True)

    return volume

# ======================================================================
# --- export.py
# ======================================================================





def crop_and_downsample(
    volume: np.ndarray,
    slice_buffer: int,
    buffer_depth: int,
    dsf: int,
) -> np.ndarray:
    """Port of the ``VoxelMatrix(Xmin:dsf:Xmax, ...)`` crop.

    The crop trims the in-plane edges (where the disk dilation runs off the
    image and leaves artifacts) and the first ``bufferDepth`` slices (which are
    noisy because the end-cap random walk hasn't settled).

    Index translation is the fiddly part. MATLAB's ``a:step:b`` is 1-based and
    inclusive of ``b``; the 0-based equivalent is ``[a-1 : b : step]``.

    Parameters
    ----------
    volume
        ``(voxel_depth, H, W)`` boolean volume from :func:`build_voxel_matrix`.
    """
    depth, H, W = volume.shape

    # MATLAB: Xmin = sliceBuffer, Xmax = size(BW,1) - sliceBuffer
    r = slice_buffer                       # 1-based start -> 0-based index r-1
    r_max, c_max = H - slice_buffer, W - slice_buffer

    return volume[
        buffer_depth - 1 : depth : dsf,
        r - 1 : r_max : dsf,
        r - 1 : c_max : dsf,
    ]


def to_uint8(volume: np.ndarray) -> np.ndarray:
    """Port of ``uint8(outputMatrix * 255)``.

    PlantVG.m accumulates overlapping cells by *addition*, so ``VoxelMatrix`` can
    hold values above 1; ``uint8(x*255)`` then saturates every one of them to
    255. Carrying a boolean volume and mapping True -> 255 is therefore
    bit-identical, and avoids the intermediate float volume entirely.
    """
    return np.where(volume, np.uint8(255), np.uint8(0))


def write_tiff(volume: np.ndarray, path) -> None:
    """Port of the ``imwrite(..., 'WriteMode', 'append')`` loop.

    Writes a single multi-page TIFF, one page per slice, readable by ImageJ.
    """

    __import__("tifffile").imwrite(str(path), to_uint8(volume), photometric="minisblack")

# ======================================================================
# --- pipeline.py
# ======================================================================


from dataclasses import dataclass, field
from pathlib import Path





# ---------------------------------------------------------------------------

@dataclass
class Parameters:
    """The eight fields of PlantVG.m's ``inputdlg``, plus the two selections
    that were separate dialogs, plus a seed.

    ``voxel_depth`` is the depth the *user* asks for. The working depth adds a
    buffer of ``2*radius + wall_thickness`` slices, which are cropped off at
    export because the end-cap random walk hasn't settled there yet.
    """

    voxel_depth: int = 100
    wall_thickness: int = 4
    wall_variation: int = 0
    radius: int = 2
    length_factor: float = 1.0
    output_name: str = "Output Voxel Mesh"
    dsf: int = 1
    n_models: int = 1
    distribution: str = "Normal"
    seed: int | None = None

    # Derived, matching PlantVG.m's arithmetic.
    @property
    def buffer_depth(self) -> int:
        return int(np.ceil(2 * self.radius + self.wall_thickness))

    @property
    def working_depth(self) -> int:
        return int(np.ceil(self.voxel_depth)) + self.buffer_depth

    @property
    def slice_buffer(self) -> int:
        return int(np.ceil(self.radius + self.wall_thickness))

    def output_shape(self, image_shape: tuple[int, int]) -> tuple[int, int, int]:
        """Predict the exported volume shape without generating it."""
        H, W = image_shape
        n = lambda a, b: len(range(a - 1, b, self.dsf))
        return (
            n(self.buffer_depth, self.working_depth),
            n(self.slice_buffer, H - self.slice_buffer),
            n(self.slice_buffer, W - self.slice_buffer),
        )

    def validate(self) -> list[str]:
        """Return a list of problems, empty if the parameters are usable."""
        problems = []
        if self.wall_thickness < 1:
            problems.append("wall thickness must be at least 1 pixel")
        if self.radius < 1:
            problems.append("end cap radius must be at least 1 pixel")
        if self.dsf < 1:
            problems.append("downsample factor must be at least 1")
        if self.n_models < 1:
            problems.append("number of models must be at least 1")
        if self.wall_variation < 0:
            problems.append("wall variation cannot be negative")
        if self.distribution not in DISTRIBUTIONS:
            problems.append(f"distribution must be one of {DISTRIBUTIONS}")
        return problems


@dataclass
class PreparedImages:
    """Traced transverse and longitudinal inputs."""

    transverse: np.ndarray
    longitudinal: np.ndarray
    boundaries: list[np.ndarray]
    boundaries_long: list[np.ndarray]

    @property
    def shape(self) -> tuple[int, int]:
        return self.transverse.shape

    @property
    def n_cells(self) -> int:
        return len(self.boundaries)


@dataclass
class LengthModel:
    """Fitted cell-length distribution plus the data behind it."""

    raw_heights: np.ndarray
    counted: np.ndarray
    heights: np.ndarray
    avg: float
    std: float
    fitted: FittedDistribution = field(repr=False)


# ---------------------------------------------------------------------------

def prepare_images(
    transverse_path,
    longitudinal_path,
    invert_transverse: bool = False,
    invert_longitudinal: bool = False,
) -> PreparedImages:
    """Sections 1-2: load, binarize, optionally invert, fill holes, trace.

    ``invert_*`` replaces PlantVG.m's ``while ~isCorrect`` confirmation loops.
    In a notebook the user inspects the overlay and re-runs the cell with the
    flag flipped, which is the same decision without the blocking prompt.
    """
    _, bw_t = read_binary_image(transverse_path)
    _, bw_l = read_binary_image(longitudinal_path)

    if invert_transverse:
        bw_t = ~bw_t
    if invert_longitudinal:
        bw_l = ~bw_l

    filled_t = imfill_holes(bw_t)
    filled_l = imfill_holes(bw_l)

    return PreparedImages(
        transverse=filled_t,
        longitudinal=filled_l,
        boundaries=bwboundaries(filled_t),
        boundaries_long=bwboundaries(filled_l),
    )


def analyze_lengths(
    prepared: PreparedImages,
    lower: float | None = None,
    upper: float | None = None,
    length_factor: float = 1.0,
    distribution: str = "Normal",
) -> LengthModel:
    """Sections 3-4: cell heights, outlier filter, distribution fit."""
    raw, counted = cell_heights(prepared.boundaries_long, prepared.longitudinal.shape[0])
    if raw.size == 0:
        raise ValueError(
            f"None of the {len(prepared.boundaries_long)} cells in your longitudinal "
            "image can be measured, because every one of them runs off the top or "
            "bottom edge. A cell that is cut off by the edge has an unknown true "
            "length, so it cannot be used.\n\n"
            "Try a longitudinal image that shows whole cells with some blank space "
            "above and below them, or zoom out so more complete cells are visible."
        )

    heights, avg, std = filter_heights(raw, lower, upper, length_factor)
    fitted = fit_distribution(heights, distribution)
    return LengthModel(raw, counted, heights, avg, std, fitted)


def generate_models(
    prepared: PreparedImages,
    lengths: LengthModel,
    params: Parameters,
    output_dir=".",
    progress=None,
) -> list[Path]:
    """Sections 5-7, looped over ``params.n_models``.

    Each model redraws both the end-cap positions and the per-cell wall
    thickness variation, so a single pair of input slides yields as many
    statistically distinct models as asked for -- the bootstrapping the
    manuscript describes.

    Parameters
    ----------
    progress
        Optional ``callable(model_index, n_models, stage)`` for UI feedback.
    """
    problems = params.validate()
    if problems:
        raise ValueError("invalid parameters: " + "; ".join(problems))

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(params.seed)
    written: list[Path] = []

    for quant in range(1, params.n_models + 1):
        if progress:
            progress(quant, params.n_models, "end caps")
        caps = generate_end_caps(
            prepared.n_cells, params.working_depth, lengths.fitted, lengths.avg, rng
        )

        if progress:
            progress(quant, params.n_models, "voxel matrix")
        volume = build_voxel_matrix(
            prepared.boundaries, caps, prepared.shape, params.working_depth,
            params.wall_thickness, params.wall_variation, params.radius, rng,
        )

        if progress:
            progress(quant, params.n_models, "writing tiff")
        out = crop_and_downsample(
            volume, params.slice_buffer, params.buffer_depth, params.dsf
        )
        path = output_dir / f"{params.output_name}-{quant}.tiff"
        write_tiff(out, path)
        written.append(path)

    return written
